apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: dejandeveloper/hotel:2
        command: ["bundle exec sidekiq"]
        env:
        - name: REDIS_URL
          value: "redis://my-redis-master.default.svc.cluster.local:6379/1"
