development:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>/1

test:
  adapter: test

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_USERNAME'] %>:<%= ENV['REDIS_PASSWORD'] %>@<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] %>/1



