default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: hotel-development

test:
  <<: *default
  database: hotel-test

production:
  <<: *default
  database: hotel-production





