default: &default
  adapter: postgresql
  encoding: unicode
  username: dejan
  password: udji
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_development

test:
  <<: *default
  database: hotel_test

production:
  <<: *default
  database: hotel_production
  password: <%= ENV["HOTEL_DATABASE_PASSWORD"] %>