default: &default
  adapter: postgresql
  encoding: unicode
  username: dejan
  password: udji
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_development

test:
  <<: *default
  database: hotel_test

production:
  <<: *default
  database: hotel_production