default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dejan_hotel_2uca_development
  username: dejan_hotel_2uca_user
  password: U9YVoskDsSjSxYcZltKS8AtVW6jXMImT
  url: postgres://dejan_hotel_2uca_user:U9YVoskDsSjSxYcZltKS8AtVW6jXMImT@dpg-ckf813mafg7c738l2llg-a.frankfurt-postgres.render.com/dejan_hotel_2uca

test:
  <<: *default

  database: dejan_hotel_2uca_development
  username: dejan_hotel_2uca_user
  password: U9YVoskDsSjSxYcZltKS8AtVW6jXMImT
  url: postgres://dejan_hotel_2uca_user:U9YVoskDsSjSxYcZltKS8AtVW6jXMImT@dpg-ckf813mafg7c738l2llg-a.frankfurt-postgres.render.com/dejan_hotel_2uca

production:
  <<: *default
  
   
  database: dejan_hotel_2uca_development
  username: dejan_hotel_2uca_user
  password: U9YVoskDsSjSxYcZltKS8AtVW6jXMImT
  url: postgres://dejan_hotel_2uca_user:U9YVoskDsSjSxYcZltKS8AtVW6jXMImT@dpg-ckf813mafg7c738l2llg-a.frankfurt-postgres.render.com/dejan_hotel_2uca
