default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dejan
  password: udji12345
  host: localhost

development:
  <<: *default
  database: hotel

test:
  <<: *default
  database: hotel

production:
  <<: *default
  database: hotel 





