default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dejan
  host: localhost

development:
  <<: *default
  database: hotel-development
  password: udji

test:
  <<: *default
  database: hotel-test
  password: udji

production:
  <<: *default
  database: hotel-production
  password: udji12345





