default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_development


test:
  <<: *default
  database: hotel_test


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>