concurrency: 5
queues:
  - default
  - [mailers, 2]
:scheduler:
  :schedule:
    send_reminder_messages:
      every: '1d'
      cron: '0 10 * * *'
      class: 'Reservation'
      queue: mailers
      args:
        - send_reminder_emails