name: Actions

on: pull_request

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true 
      - name: Set up Node
        uses: actions/setup-node@v3 
        with:
          node-version: 18
      - name: Setup Standard
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          npm install
      - name: Vite Build
        run: vite build   
      - name: Standard Report
        run: bundle exec standardrb
  vite_build:
    name: Vite Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Vite dependencies
        run: npm install
      - name: Vite Build
        run: npm run build
  eslint:
    # ... (your existing eslint configuration)
  nodechecker:
    # ... (your existing nodechecker configuration)
  test:
    name: RSpec
    needs: vite_build  # Ensure Vite build is completed before running RSpec
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: kindergarten_exchange_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/starter_rails_api_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true
  
      - name: Create database tables
        run: bin/rails db:create
      - name: Set up database schema
        run: bin/rails db:schema:load
  
      - name: Run tests
        run: bin/bundle exec rspec spec
